package com.project.search.dao;

import com.project.search.model.CategoryModel;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface CategoryModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu May 21 22:42:15 EDT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu May 21 22:42:15 EDT 2020
     */
    int insert(CategoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu May 21 22:42:15 EDT 2020
     */
    int insertSelective(CategoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu May 21 22:42:15 EDT 2020
     */
    CategoryModel selectByPrimaryKey(Integer id);

    List<CategoryModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu May 21 22:42:15 EDT 2020
     */
    int updateByPrimaryKeySelective(CategoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu May 21 22:42:15 EDT 2020
     */
    int updateByPrimaryKey(CategoryModel record);

    Integer countAllCategory();
}